CREATE TABLE players (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         nickname VARCHAR(255),
                         gender VARCHAR(20),
                         phone VARCHAR(50),
                         email VARCHAR(255) NOT NULL UNIQUE,
                         password_hash VARCHAR(255) NOT NULL,
                         walk_up_song_artist VARCHAR(255),
                         walk_up_song_title VARCHAR(255),
                         walk_up_song_file_path VARCHAR(500),
                         manager BOOLEAN NOT NULL DEFAULT FALSE,
                         master_manager BOOLEAN NOT NULL DEFAULT FALSE,
                         active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE game_weeks (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            game_date DATE,
                            game_time TIME,
                            status VARCHAR(50),
                            created_at TIMESTAMP
);

CREATE TABLE password_reset_tokens (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       token VARCHAR(255) NOT NULL UNIQUE,
                                       player_id BIGINT NOT NULL,
                                       expires_at TIMESTAMP NOT NULL,
                                       used_at TIMESTAMP,
                                       CONSTRAINT fk_password_reset_tokens_player
                                           FOREIGN KEY (player_id) REFERENCES players(id)
);

CREATE TABLE player_availability (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     game_week_id BIGINT NOT NULL,
                                     player_id BIGINT NOT NULL,
                                     status VARCHAR(20),
                                     CONSTRAINT fk_player_availability_game_week
                                         FOREIGN KEY (game_week_id) REFERENCES game_weeks(id),
                                     CONSTRAINT fk_player_availability_player
                                         FOREIGN KEY (player_id) REFERENCES players(id),
                                     CONSTRAINT uk_player_availability_week_player
                                         UNIQUE (game_week_id, player_id)
);

CREATE TABLE player_preferences (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    game_week_id BIGINT NOT NULL,
                                    player_id BIGINT NOT NULL,
                                    preferred_player_id BIGINT NOT NULL,
                                    CONSTRAINT fk_player_preferences_game_week
                                        FOREIGN KEY (game_week_id) REFERENCES game_weeks(id),
                                    CONSTRAINT fk_player_preferences_player
                                        FOREIGN KEY (player_id) REFERENCES players(id),
                                    CONSTRAINT fk_player_preferences_preferred_player
                                        FOREIGN KEY (preferred_player_id) REFERENCES players(id),
                                    CONSTRAINT uk_player_preferences_week_player
                                        UNIQUE (game_week_id, player_id)
);

CREATE TABLE teams (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       game_week_id BIGINT NOT NULL,
                       color VARCHAR(255) NOT NULL,
                       name VARCHAR(255),
                       CONSTRAINT fk_teams_game_week
                           FOREIGN KEY (game_week_id) REFERENCES game_weeks(id)
);

CREATE TABLE team_roster_entries (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     team_id BIGINT NOT NULL,
                                     player_id BIGINT NOT NULL,
                                     batting_order INTEGER NOT NULL DEFAULT 0,
                                     runs_scored INTEGER NOT NULL DEFAULT 0,
                                     CONSTRAINT fk_team_roster_entries_team
                                         FOREIGN KEY (team_id) REFERENCES teams(id),
                                     CONSTRAINT fk_team_roster_entries_player
                                         FOREIGN KEY (player_id) REFERENCES players(id),
                                     CONSTRAINT uk_team_roster_entries_team_player
                                         UNIQUE (team_id, player_id)
);

CREATE TABLE game_state (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            game_week_id BIGINT NOT NULL UNIQUE,
                            current_batting_team_id BIGINT,
                            current_batter_roster_entry_id BIGINT,
                            inning INTEGER NOT NULL DEFAULT 1,
                            CONSTRAINT fk_game_state_game_week
                                FOREIGN KEY (game_week_id) REFERENCES game_weeks(id),
                            CONSTRAINT fk_game_state_current_batting_team
                                FOREIGN KEY (current_batting_team_id) REFERENCES teams(id),
                            CONSTRAINT fk_game_state_current_batter_roster_entry
                                FOREIGN KEY (current_batter_roster_entry_id) REFERENCES team_roster_entries(id)
);