-- Homepage announcement banners.
--
-- start_date/end_date are calendar dates (inclusive), which makes scheduling
-- independent of server timezone and avoids an announcement changing at 8 PM
-- because of UTC/local-time differences.
CREATE TABLE home_page_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message VARCHAR(1000) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    background_color VARCHAR(9),
    text_color VARCHAR(9),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_home_page_announcement_dates
        CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE INDEX idx_home_page_announcements_active
    ON home_page_announcements (enabled, start_date, end_date);
